development:
  adapter: async

test:
  adapter: async

production:
  adapter: postgresql
  url: postgres://ochqqndtqrwang:Jaa2H0OBUT8qy1spuXOzfYMGXu@ec2-54-163-240-204.compute-1.amazonaws.com:5432/de7qlojv0utoee
